language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: make clean && tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: domenicrosati
  password:
    secure: o4g67FxPe8gDjR6hyEhIlThg1zATSeNeswRXt8FYxrrpfJ0WDBP2sP+vv6TsRsnfgXI9kup0zDZ+pCxI+CVz32KmIeVTMd4hL2XyK2IzRPcowsvKBe9/x3Nu1UWR3h8J31IAprLg5txW3FDZtoNv/Kt3xRn5tbX8cF48DpjYUUCuAVOxQVn/QyttYo8U5KueOnd90SVcHrJUQXhcDL7VXneVJhpFvCrn5lZ2H22W79HHP7Ch0tmcdGHQTYpkmughE/eNTOTcJ57V9ZyqN9C1EyDIvDH5lmTdHbUFNZU0WNjfStT1wFoe7aNZD480PxfBo2Mo4y6Ds7MToc/6XNPig3DOOK19OZQOLqb4yxxf9DBuodfvwDor5kbeMjCv8x1lKbqOxAmS+nFzwYe8WC7xCK9VKyeHUp9lXzzd8QnslP5v1GaDI9sn0eMXjWFIAs/TOCVwntpFL2I/cCuiYKWl7eU28aJ0lLC2KtQjINC6gAiItqedhWW7Vhz+JmJUbwG55+vjn5hKlZOMKITZcBPhrdaOY+Wo7dVYBiKiqvHt5F1tAmoSORoWV3Xdh6gIi2FjaFU/pPvnb3cTT/5Dj2ejsoBE+ae2zb3hZEfPlBz0/0pfxVGGfb2YPNZT1c9fhbzV12yFYGVW7pe3qY85I/muiBM71IIR4WQ5o2LfkNUhT1Y=
  on:
    tags: true
    repo: manifoldco/pytill
    python: 3.6
