language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: make clean && tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: domenicrosati
  password:
    secure: Kf0AM96BBv1qOpD32/vv1egKqXy3icGvnE09slHQBym3Dyu43CNtCRciliKuOye3IBTJnQsidq1rZcBM35gqJtHSmbiGt1GvTneYI2CmEo/LQTG3rd4ca6rAdHCq5PZlmI+4HiantCwBmVWceVzWOHiWF8N3Uo0LeXA6bp4YdpfjMJkfwajvTa6ckQH1FNvWiksfnxcTHNy8Z181w1yNvLSHzdwewUEzu2fJd57QSqEiSWnBFRHxLwW+drxS0LgRUAtKm3LLuEeAtTJDl/jI6khJVyX4cyBBEq3JqaWegwn3D9JhM0VJtfwX+1Ks3ICcWWEqeVv4d6F0LVIMv2/HM4aem0sUtFujaRY8KtwX9GUZDPce+vgwwajLc94shysCdJCbU751wtV9bnOsfN365sVzApuirvvsu02zoEmHBS/bZUtzgljXeWTHHIZ/p++b6iRZyCTXHnQUxiOgoPJkRo88fzbNKHVZEUcR87w+9kMfSzvIkfSX+Oqq6t3NApGNGTxepgggIAyWGkjG59F3m3katUHDfnVEjcg2kwwp3yB/hx8gc97HT6c+p3QXjX+7QJXWyeRogE4CrvUtlE0D82vIg/I+ubqjlr0iM9drIWk3TwFhbOsflmnYEkXqbaQKFFJ3U/MJ9+Wu8UCtRF0A05EgP12vtCy+G7kMky2sUbw=
  on:
    tags: true
    repo: manifoldco/pytill
    python: 3.6
